### ISSUE TITLE
Missing full bed levelling output

### ISSUE THREAD

**Issue by 4nthonylin** [bbbenji/PMSBLM#1]
In step 6 when mentioning the output, please include the first row of "0 1 2 3" to ensure that people copy it over. I was confused at first and truncated it and drove me crazy when the back left screw did nothing 😅

**Comment by bbbenji** [comment]
This is what we want. As mentioned in #2 I will look into making both methods work.

Also, please note that the Mini's output and the output of the converter are mirrored. Meaning value `0 0` is the bottom left corner of the printer. Whereas in the output of the converter, the first value is the top left corner, when looking down at your printer.
