### ISSUE TITLE
Question - MK3S

### ISSUE THREAD

**Issue by jreed1701** [bbbenji/PMSBLM#14]
Will the DIN 965 torx screws and nuts  recommended for this procedure also work on an MK3S?

**Comment by bbbenji** [comment]
No. However, I believe that you can re-use the original MK3 screws. Unfortunately, that's out of the scope of this repo.

**Comment by jreed1701** [comment]
Thank you for responding. I had re-used the original MK3 screws doing this procedure on that platform and have noticed they loosen over time. Therefore I was considering torx screws as an alternative.

**Comment by bbbenji** [comment]
I think the problem is the carriage does not have nylon to lock the screw into place. Good to know that this mod night not be right for the MK3. I don't believe Torx screws would make a difference in this case.

**Comment by jreed1701** [comment]
I failed to say that I am not using nuts on the bottom with the original MK3 screws. The mod works if I make re-leveling the bed a part of maintenance routine. 

I agree. The carriage would be better designed if it had a method to secure the screw.
