### ISSUE TITLE
Right Rear corner to close but bed levling says its Fine

### ISSUE THREAD

**Issue by Plyn1x** [bbbenji/PMSBLM#16]
I did the mod and before there were no big troubles but now my right rear corner is waaay to close. But the Probe says its fine but it isn´t 
Any Ideas?)
Things I tried: 
Making the X Axis Straight to the bed 
Flipping the sheet over
Checking for debree
Heres the Rear right Corner:
![610B494B-DDD1-4A5E-BFCB-F66A048B7530](https://user-images.githubusercontent.com/77836725/169547664-37df754d-351a-4a45-ac82-e133429a5e23.jpeg)
Left rear Corner for comparison:
![39CC46F0-90CC-41A4-8F31-C701EC1D0233](https://user-images.githubusercontent.com/77836725/169547811-3b39c9d5-3d45-4a0b-b922-ab14d0fb4960.jpeg)
My Assembly Looks like this:
![BA0E3BEA-8FDC-4517-BD26-9C66249A9EB9](https://user-images.githubusercontent.com/77836725/169547865-52352b92-94f4-49bb-9b5d-3d8a1b38be1c.jpeg)

**Comment by BenHartwich2005** [comment]
Thats what he printer spits out:
 `
0 -0.091 -0.071 -0.026 -0.007
1 -0.089 +0.002 -0.049 -0.013
2 -0.038 +0.022 -0.052 -0.012
3 -0.063 -0.011 -0.005 -0.019
`

**Comment by Plyn1x** [comment]
![image](https://user-images.githubusercontent.com/77836725/169548432-7dce2fa1-303b-4f34-85f2-d50a4cc869ab.png)

**Comment by bbbenji** [comment]
I've seen something similar when the toolhead was depressing the heated bed cable cover. Please check for this and let me know.

**Comment by bbbenji** [comment]
By looking closer at the pictures, looks like you are referring to the front right side? Hmm, not sure in this case. Perhaps a faulty SPINDA cable?

**Comment by Plyn1x** [comment]
I checked it seems to be fine no interruptions

**Comment by Plyn1x** [comment]
I just tried squaring my Mini and it seens to be better now
https://help.prusa3d.com/article/squaring-your-mini_158518
