### ISSUE TITLE
Suggestion: Reference the model "Prusa MINI Silicone Bed Leveling Mod - bed tightening jig" to help adjustments

### ISSUE THREAD

**Issue by pickworthi** [bbbenji/PMSBLM#17]
The model is on printables here: [https://www.printables.com/model/43629-prusa-mini-silicone-bed-leveling-mod-bed-tightenin](url)

Without it, I don't think I would have guessed how much to turn each adjustment very accurately - so it is definitely a help in my view.

I would suggest adding a link to it in the Requirements section - as an optional tool.

**Comment by bbbenji** [comment]
Feel free to submit a PR with the change :)

**Comment by pickworthi** [comment]
This is the very first time I have done a Pull Request on Github - I hope it's done the right way.

**Comment by bbbenji** [comment]
Perfect! Thank you.
