### ISSUE TITLE
Wrong silicon tube in the manual

### ISSUE THREAD

**Issue by islonina** [bbbenji/PMSBLM#19]
U cant use silicon from:
https://fmic.pl/laczniki-silikonowe/193-5923-przewod-podcisnienia-3mm-vacuum.html
The tube is 9.8mm OD

**Comment by bbbenji** [comment]
This is the exact tubing I ordered and have been using since the inception of this guide and can verify it's 8mm OD.
How do you know its 9.8mm?I don't see the OD mentioned in the product listing anywhere.
Did you order this and receive 9.8mm OD?

**Comment by islonina** [comment]
I order this 2 times and its always 9.8. Calling fmic its there standard for some time so that change. No problem i just redesigne cuting jig and all works fine

**Comment by Preclowski** [comment]
Does it matter that much? 3x6 ior 3x9 would not work with this mod?

**Comment by bbbenji** [comment]
3x6 might be ok, I haven't tried. 3x9 might be too tough to compress.
