### ISSUE TITLE
Command language

### ISSUE THREAD

**Issue by hazelra** [bbbenji/PMSBLM#20]
I noticed a ' at the end of the one command (G28 ; home all without mesh bed level`)  Is that correct?

**Comment by bbbenji** [comment]
No, it's not correct, but it also doesn't matter. Including and everything after `;` is a comment and ignored by the printer.

**Comment by hazelra** [comment]
I did not realize that it was only the G# that the printer reads. I ran the code several times and it worked great. One time I ran it and maybe I did it out of order. The printer was not homed, I ran the mesh bed level command. The print head crashed into the print bed and dented the print bed. I don't exactly remember what I did. So now I home on the printer first using the control panel on the printer, then run the bed level command on the Pronterface. This is not a criticism, just wanted to post it so others don't make my mistake.
