### ISSUE TITLE
Screw length makes it hard to get nuts threaded

### ISSUE THREAD

**Issue by hazelra** [bbbenji/PMSBLM#21]
I used the 16mm screws and cut the tubing with the jig (10mm), but it was super hard to press the heat bed and tubing down to get the screw threaded onto the nut. I ended up cutting 2mm off the tubing. I think 18mm or 20mm screws would work and make things easier. Thanks for writing this up, it's awesome and worked really well.

**Comment by bbbenji** [comment]
Glad the guide was helpful, but you really should use 10mm of tubing. Longer screws will catch on the frame.

**Comment by hazelra** [comment]
Yes, you are right. I just realized the back center screw has very little clearance past the nut. (which is in your notes that I overlooked) Did you struggle with compressing the 10mm tubing. How did you do it? I had a very difficult time compressing it enough to get it threaded on the nut.

**Comment by bbbenji** [comment]
I've had no issues with mounting the heated bed. I have read that someone used clamps to help them. However, I don't recommend that as it would be easier to cause damage.
