### ISSUE TITLE
Converter averaging results?

### ISSUE THREAD

**Issue by arklan** [bbbenji/PMSBLM#23]
see image here: https://forum.prusa3d.com/forum/postid/654405/

Octoprint is showing my bed is a wave, with a significant low followed by a significant high. when averaged out, things are level, as the converter, despite plotting correctly, shows little or no adjustment needed. 

I'm not totally sure this is an issue with the converter, mind you.

**Comment by bbbenji** [comment]
Pasting for future reference:

```
0 +0.056 -0.033 +0.142 -0.017
1 +0.035 -0.030 +0.393 -0.003
2 +0.095 -0.240 +0.105 -0.018
3 +0.046 -0.186 +0.322 +0.042
```

**Comment by bbbenji** [comment]
@arklan I just spent a minute actually looking at your issue and you are correct in your assumption. 

On that note, there really isn't anything we can do to help in this case when it comes to the converter. You must first resolve the wave in your bed before continuing with this guide.

For reference, here is how the measurements are averaged: 
![IMG_0008](https://user-images.githubusercontent.com/1678118/235501914-66947f25-212d-4df2-914b-464af404d3a1.jpeg)

**Comment by arklan** [comment]
Right, no worries. Wave in my bed was due to bad tightening, which was result of an intermitent failure on the pinda when on the far left. 

At least I think. failing probe for sure.

thanks!

**Comment by bbbenji** [comment]
I never got an exact answer to how much a S/PINDA can physically and sensibly compensate. But it's can only do so much.
