### ISSUE TITLE
Aliexpress source for low-profile nylocks?

### ISSUE THREAD

**Issue by kozross** [bbbenji/PMSBLM#24]
I'd like to do this mod, but I cannot find AXIC1052 _anywhere_. Amazon delivery here is hilariously expensive (more than the item in question), and the only nylock nuts I can find are about 4mm tall.

**Comment by bbbenji** [comment]
Sorry, I don't know of any sources. But no worries, in practice you just need a single low-profile nylock at the center back, you need to make sure it clears the Y-axis motor mount. It's no biggie, really - just a few minutes of sanding down a regular nylock on some sandpaper should do the trick.

If anyone stumbles upon a source for these nuts, feel free to update the docs with a link via a PR.
