### ISSUE TITLE
Would 4mm ID tubing work?

### ISSUE THREAD

**Issue by kozross** [bbbenji/PMSBLM#25]
I'm in actual sourcing hell, and the best I've been able to find locally whose temperature resistance I can verify is 4mm ID, 7mm OD. Would this work, or is 3mm ID essential?

**Comment by kozross** [comment]
Before the obvious questions: no, Amazon don't ship the linked tubing here, and even if they did, it'd cost more to ship than the tubing by a factor of like 4.

**Comment by kozross** [comment]
Alternatively, would tubing [like this](https://www.aliexpress.com/item/1005003679801403.html) be suitable?

**Comment by bbbenji** [comment]
I wouldn't use those. A smaller or larger outer diameter might be ok, but I would keep with 3mm inner diameter.
