### ISSUE TITLE
DIN 7991 not working for me

### ISSUE THREAD

**Issue by bstansell** [bbbenji/PMSBLM#27]
Found that #3 mentions "the 16mm screws are DIN 965 or DIN 7991", which I'm assuming is why the guide says either works.  My experience says DIN 7991 does not work - they ride just a bit above the head bed.  Looking online, the head size for DIN 965 is [5.3 to 5.6](https://www.fasteners.eu/standards/DIN/965/), whereas DIN 7991 is [5.7 to 6](https://www.fasteners.eu/standards/DIN/7991/).  Perhaps the holes in some of the heat beds are a bit deeper and DIN 7991 can work, but certainly not with mine.

I'm waiting on some DIN 965 now, and I'm sure that'll work.  Maybe I'm unlucky, but you may want to add a warning or remove the 7991 reference.  🤷 

Thanks for the whole thing...awesome mod!

**Comment by bstansell** [comment]
Update: Got my DIN 965 screws, and they work beautifully.  Just can't see how DIN 7991 can really work.

**Comment by bbbenji** [comment]
Updated. Thanks.
