### ISSUE TITLE
Updates/ clarification for the documentation

### ISSUE THREAD

**Issue by hbast** [bbbenji/PMSBLM#30]
Thanks for the tremendous work! I already installed the mod 1-2 years ago and just came back to recalibrate the bed. I noticed several things that should be adjusted in the documentation:

1) Replace vs. re-place vs. put back? Well, I'm not a native speaker and I'm not 100% sure what exactly is meant by "replace" (Make sure you replace your steel sheet). Presumably it means that the steel sheet should be put back on the heating bed. It would be nice if this could be formulated more clearly.

2) Can you please expand the text to say that the link provided should be used for the old firmware and the new link (beta) for the new firmware? It took me quite some time to figure that out.

**Comment by bbbenji** [comment]
Should be good now. Closing.
